### ISSUE TITLE
File structure for a java program doesn't match Bazel docs

### ISSUE THREAD

**Issue by Jdban** [google/startup-os#147]
Docs here: https://docs.bazel.build/versions/master/bazel-and-java.html#directory-structure

> Prefer Maven's standard directory layout (sources under src/main/java, tests under src/test/java)

Which is preferred? If you have 100 projects, I am having a hard time picturing how it looks in a single repository

**Comment by oferb** [comment]
That's a valid point. Not sure about that recommendation. I've put up a question for the Bazel team:
https://groups.google.com/forum/#!topic/bazel-discuss/e3Qsg-He2bg

Note that we've had a similar discussion in this issue:
https://github.com/google/startup-os/issues/30
but I wasn't aware of that doc recommendation at the time.

**Comment by oferb** [comment]
Didn't get an answer, but if it ends up being a problem, we can always add `src/main/java` and `src/test/java` as parent folders.
Closing for now.
