### ISSUE TITLE
gRPC server should return diff information

### ISSUE THREAD

**Issue by oferb** [google/startup-os#15]
We should add a new command for the local gRPC server that, given 2 files, returns them and their diff.
Here's the server:
https://github.com/google/startup-os/tree/master/tools/reviewer/local_server
Here's the text diff:
https://github.com/google/startup-os/blob/master/common/TextDifferencer.java

The server response should include both the compared files and their diff.

**Comment by yanivsn** [comment]
#40 pull request was created.
