### ISSUE TITLE
Tools folder needs more documentation

### ISSUE THREAD

**Issue by Jdban** [google/startup-os#156]
Looking in the tools folder, there seem to be some interesting tools, but there is no documentation. What is `aa`? What is `buildtools_wrapper`? Ideally, we don't have to hunt through the source code to find out, so some documentation would be great.

**Comment by oferb** [comment]
You're right! Thanks for pointing it out.
I'm adding documentation about the tools :)

**Comment by oferb** [comment]
Here's some basic documentation: https://github.com/google/startup-os/tree/master/tools
I added some issues to organize and simplify the tools (e.g consolidate different formatters into one tool), and then I'll update it.

**Comment by Jdban** [comment]
LGTM. You can probably close this issue then

**Comment by oferb** [comment]
Thanks :)
I'll keep this issue around to update the tooling documentation after the simplifications, then I'll close it.

**Comment by oferb** [comment]
and... done.
