### ISSUE TITLE
Move `android` folder to under `examples`

### ISSUE THREAD

**Issue by oferb** [google/startup-os#160]
Current location: https://github.com/google/startup-os/tree/master/android

**Comment by NikleshPhabiani** [comment]
I can take this up. The package names and the imports too will have to be changed, right?

**Comment by oferb** [comment]
Great!
Yah, package names have to be changed. Imports have to be changed too, but there the compiler will complain until it's fixed.

**Comment by NikleshPhabiani** [comment]
Cool. I'll go ahead with the changes. Also, what do you think about making 'examples' folder while traversing to the source code i.e inside /android/src/main/java/com/google/startupos?

**Comment by oferb** [comment]
Good question.
You could change it into just:
/examples/android
The package name then be:
com.google.startupos.examples.android

**Comment by oferb** [comment]
Thanks Niklesh!
