### ISSUE TITLE
Unable to run `bazel query //...` on StartupOS

### ISSUE THREAD

**Issue by jbduncan** [google/startup-os#173]
I'm not sure where else to report this bug I've encountered, so if it isn't the right place, would someone from the StartupOS team kindly point me in the right direction?

Problem
===

After forking and cloning StartupOS to my Windows computer, if I try to run `bazel query //...` (part of the [installation instructions](https://github.com/google/startup-os#installation)), I encounter the following error:

> ERROR: error loading package '': Encountered error while reading extension file 'defs.bzl': no such package '@build_bazel_rules_typescript//': No WORKSPACE file found in C:/users/jonathan/_bazel_jonathan/zjfrytj2/external/build_bazel_rules_typescript

When I navigate to `C:/users/jonathan/_bazel_jonathan/zjfrytj2/external/build_bazel_rules_typescript`, Windows throws up the following error message box:

![image](https://user-images.githubusercontent.com/2482228/42714279-7e405f40-86ea-11e8-9c59-44d833d11173.png)

How to reproduce
===

1. `git clone https://github.com/jbduncan/startup-os`
2. `cd startup-os`
3. `bazel query //...`

Environment
===

Operating System
---
Windows 7

`bazel version`
---

```
Build label: 0.15.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jun 26 12:09:42 2018 (1530014982)
Build timestamp: 1530014982
Build timestamp as int: 1530014982
```

**Comment by vmax** [comment]
@jbduncan did you run `npm install`?

**Comment by jbduncan** [comment]
Oops! I did install node.js, but that's the step I forgot. 😫

I'll give that a go and let you know how it goes once I'm next free.

**Comment by jbduncan** [comment]
Seems to be working, now. Thanks @vmax! :)
