### ISSUE TITLE
Add yapf and clang-format to formatter

### ISSUE THREAD

**Issue by vmax** [google/startup-os#177]
`//tools:formatter` currently relies on `yapf` and `clang-format` being available on the user's system.
We should make a BUILD target that will make `bazel` download them, and then add them to `runtime_deps` of `//tools:formatter`, so that they're available to the tool to use.

**Comment by NikleshPhabiani** [comment]
I would want to try out this one.

**Comment by oferb** [comment]
Ok, go ahead :)

**Comment by vmax** [comment]
@NikleshPhabiani for reference, you can have a look at how [`//tools:protoc`](https://github.com/google/startup-os/blob/master/tools/BUILD#L36) is implemented. Remember it should work at both platforms (Linux/macOS). Ping me if you need any help 🙂

**Comment by NikleshPhabiani** [comment]
@vmax . Actually, I did happen to look at how `//tools:protoc` is implemented a few days and looked something that would help me out in this issue but haven't looked at it lately. Thanks a lot for the update. Yes, will definitely let you know if I need any help.

**Comment by NikleshPhabiani** [comment]
A snippet for installation of clang-format on macOS:
```bash
platform=$(uname)

if [ "$platform" == "Darwin" ]; then
  mkdir -p ./clang-format
  curl 'http://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-apple-darwin.tar.xz' -o './clang-format/clang-format.tar.xz'
  tar xvfj clang-format/clang-format.tar.xz -C ./clang-format
  rm -f ~/bin/clang-format
  ln -s $(pwd)/$(find clang-format | grep bin/clang-format$) ~/bin/clang-format
fi
```

[Reference Link](https://staxmanade.com/2015/01/how-to-install-clang-format-and-formatting-objective-c-files/)

Is this fine or is something else expected? The other relevant files will be changed but this is just a snippet for installation on the system. Also, which binary from the [releases](http://releases.llvm.org/download.html) needs to be used for installation on Linux? Thanks.

**Comment by oferb** [comment]
So the idea is to have bazel get the binary. That way no setup step is needed from the developer.
If you look at https://github.com/google/startup-os/blob/master/tools/BUILD#L36
It uses `protoc_bin` which is defined in `WORKSPACE`.

**Comment by oferb** [comment]
Hey, how's it going?

**Comment by NikleshPhabiani** [comment]
Hey. Sorry, couldn't work on this during the week. I will get this done early in the weekend. Oh ok, got it. Thanks a lot. One doubt. What would be the SHA-256 code for these? I couldn't figure out a way yet to retrieve a tag for each.

**Comment by oferb** [comment]
That's fine, just checking.
About SHA-256, we use this:
https://github.com/google/startup-os/blob/master/WORKSPACE#L1-L2
Thanks again!

**Comment by vmax** [comment]
@NikleshPhabiani One more SHA-256 tip: if you don't specify it, `bazel` will print it out on building the target that depends on that archive

**Comment by NikleshPhabiani** [comment]
Thanks a lot for all the help. I have a doubt regarding YAPF. The [release](https://github.com/google/yapf/releases/tag/v0.22.0) does not have separate versions for Linux and macOS. Is it platform independent and linked directly to Python? Kindly let me know what needs to be done with respect to YAPF.

**Comment by vmax** [comment]
@NikleshPhabiani it'll be great to use it as `http_archive` together with writing custom `BUILD` file with `py_binary` target in it

**Comment by oferb** [comment]
`clang-format` is now fully added. Thanks Niklesh! Do you want to continue this task for YAPF?
I believe that YAPF is platform-independent.

**Comment by NikleshPhabiani** [comment]
Actually, I am extremely tied up for sometime with university coursework and interviews. Hence, won't be able to pick this up atleast for the next couple of days.

**Comment by oferb** [comment]
That's fine. I created an issue just for yapf https://github.com/google/startup-os/issues/304
You're welcome to take a look, but just know that the python task is a P3 (lower priority), since we don't currently use python. There's other issues that are good `first good issue` (although you're not a first contributor anymore ;) you're welcome to take a look.

More details about P3 and other priorities: https://developers.google.com/issue-tracker/concepts/issues
