### ISSUE TITLE
Revert prefixing of mvn dependencies

### ISSUE THREAD

**Issue by vmax** [google/startup-os#238]
Pull request #235 introduces prefix to each generated target for Maven dependencies. We did this in order to avoid clashes with [rules_closure](https://github.com/bazelbuild/rules_closure) that we're using in [startup-os-example](https://github.com/oferb/startup-os-example). Investigate whether we could revert it while still maintaining both repos working.

**Comment by webdevelopland** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Set create_timestamp to local machine time when creating a new Diff. New proto field should be added for that.](https://trello.com/c/GGBAzxUR/2-set-createtimestamp-to-local-machine-time-when-creating-a-new-diff-new-proto-field-should-be-added-for-that)
