### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by oferb** [google/startup-os#290]

**Comment by oferb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support Windows](https://trello.com/c/kUw5vmCC/18-support-windows)

**Comment by oferb** [comment]
See related - https://github.com/bazelbuild/buildtools/issues/375

**Comment by oferb** [comment]
See related issue for grpc_java_plugin: https://github.com/grpc/grpc-java/issues/4859

**Comment by val-fed** [comment]
# **Windows Subsystem for Linux (WSL)**
  
The Windows Subsystem for Linux lets developers run GNU/Linux environment -- including most command-line tools, utilities, and applications -- directly on Windows, unmodified, without the overhead of a virtual machine.

### How to install?
Please follow the guide - https://docs.microsoft.com/en-us/windows/wsl/about
Note: You may have to upgrade the version of Windows. If you need it you will know about it at the very beginning of the installation.

### How to use `StartupOS` in WSL?
Just to follow instructions - https://github.com/google/startup-os#how-to-use-startupos

### Productivity testing in the same machine:
Execution time `./build.sh`
```
Ubuntu:
INFO: Elapsed time: 115.979s, Critical Path: 46.37s
INFO: 520 processes: 384 linux-sandbox, 56 local, 80 worker.
INFO: Build completed successfully, 806 total actions

Ubuntu on Windows:
INFO: Elapsed time: 471.787s, Critical Path: 102.78s
INFO: 605 processes: 494 processwrapper-sandbox, 111 worker.
INFO: Build completed successfully, 782 total actions
```

Execution time `./test.sh`
```
Ubuntu:
INFO: Elapsed time: 24.577s, Critical Path: 24.08s
INFO: 15 processes: 13 linux-sandbox, 2 local.
INFO: Build completed successfully, 16 total actions

Ubuntu on Windows:
INFO: Elapsed time: 147.112s, Critical Path: 145.24s
INFO: 15 processes: 2 local, 13 processwrapper-sandbox.
INFO: Build completed successfully, 16 total actions
```

**Comment by oferb** [comment]
Looks great!
Please add documentation on Platforms:
https://github.com/google/startup-os#platforms
