### ISSUE TITLE
Reviewer UI/UX changes

### ISSUE THREAD

**Issue by oferb** [google/startup-os#291]
* Comments summary in diff page - including general Diff comments.
* Comments in text diff page - including "Resolve" button.
* Delete Diff button
* "Request Review" button.

**Comment by oferb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Reviewer design changes](https://trello.com/c/XoUhdPbx/19-reviewer-design-changes)

**Comment by webdevelopland** [comment]
#342

**Comment by webdevelopland** [comment]
#356

**Comment by webdevelopland** [comment]
This issue is finally done
:tada: :tada: :tada: :tada:
