### ISSUE TITLE
Ability to choose exact commits in Reviewer text diff

### ISSUE THREAD

**Issue by oferb** [google/startup-os#293]
* Each code block in file-changes should be able to be picked with exact commit (not only base and last)
* Possible UI implementation: drop-down list.
* Url should store left and right state.
* Clicking on a comment would open up the text diff. It will be on the right, if it's last commit, or on the left, if there was some updates, after the comment.

#333

**Comment by oferb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ability to choose exact commit](https://trello.com/c/QGSr57iP/14-ability-to-choose-exact-commit)

**Comment by webdevelopland** [comment]
#333
