### ISSUE TITLE
Various text diff fixes

### ISSUE THREAD

**Issue by oferb** [google/startup-os#313]
Fixes to make these diff look right:
![image](https://user-images.githubusercontent.com/5137671/45545754-f050e680-b823-11e8-9bee-8571c677a2cd.png)
![image](https://user-images.githubusercontent.com/5137671/45545816-0eb6e200-b824-11e8-9955-1f1525a6fff3.png)
Taken from:
https://startupos-5f279.firebaseapp.com/diff/207/startup-os/tools/reviewer/service/CodeReviewService.java

Seems like we should be marking the corresponding line that was not changed:
![image](https://user-images.githubusercontent.com/5137671/45545871-2ee6a100-b824-11e8-8d6a-c2625a606a5e.png)
Taken from:
https://startupos-5f279.firebaseapp.com/diff/207/startup-os/examples/docker/HelloServer.java
It should be similar to standard diffs.

**Comment by webdevelopland** [comment]
https://startupos-5f279.firebaseapp.com/diff/301/startup-os/examples/docker/HelloServer.java
https://startupos-5f279.firebaseapp.com/diff/301/startup-os/examples/docker/CodeReviewService.java
