### ISSUE TITLE
Make some tests

### ISSUE THREAD

**Issue by webdevelopland** [google/startup-os#334]
PR: #567
Reviewer webapp becomes bigger and bigger.
Unit tests could reduce time of future development.

**Comment by oferb** [comment]
Ok. Feel free to add tests.
I tend to add tests if something is easily testable (and complex enough), or just before I start changing something. So you can actually add tests as part of other tasks, it doesn't have to be a special task, especially for unit tests.

**Comment by oferb** [comment]
I especially like to add tests before refactor. Maybe it's time for a refactor for Reviewer, to simplify it?

**Comment by webdevelopland** [comment]
Sounds great! :slightly_smiling_face:
