### ISSUE TITLE
Create instructions for installing `aa`

### ISSUE THREAD

**Issue by oferb** [google/startup-os#504]
These should roughly be:
1. Clone to some location
2. Build & Test (./test.sh)
3. Set up base folder:
https://github.com/google/startup-os/blob/master/tools/reviewer/aa/commands/InitCommand.java#L31
4. Set up `.bashrc`:
https://github.com/google/startup-os/blob/master/tools/reviewer/aa/aa_tool.sh#L4
5. Delete repo that was cloned
6. Build & Test from `base/head`

This should be a script, but can start off as a set of instructions.

**Comment by val-fed** [comment]
#505
