### ISSUE TITLE
Create instructions for getting a Firebase token to your local machine

### ISSUE THREAD

**Issue by oferb** [google/startup-os#506]
The rough outline is:
1. Install `aa`
2. From inside your base folder, run aa, to start up the local aa server.
3. Sign in at https://web-login-startupos.firebaseapp.com
4. Check that you have a file at `~/.aa_token`

These instructions should be added right after the instructions to install `aa` in a "Get a Firebase token on your machine".

**Comment by LiadAzulay** [comment]
which command i need to provide to start up local aa server?

**Comment by val-fed** [comment]
> which command i need to provide to start up local aa server?

You can use:
1) `bazel build //tools/reviewer/local_server:local_server`
2) `bazel-bin/tools/reviewer/local_server/local_server`

https://github.com/google/startup-os/blob/f602b23755f8b4ec18648f682bae5f61a05ea405/tools/reviewer/local_server/LocalServer.java#L45
