### ISSUE TITLE
Is there any way to use MessageDifferencer from this repo by adding a maven dependency in my code?

### ISSUE THREAD

**Issue by sumitbh250** [google/startup-os#579]

**Comment by oferb** [comment]
Hey :)
Nope, it's not packaged.
It's taken from here though:
com.google.common.truth.extensions.proto.MessageDifferencer
So maybe you can get it from there:
https://mvnrepository.com/artifact/com.google.truth/truth

**Comment by sumitbh250** [comment]
@oferb Thanks for the quick response. I went through that repo too, but in that repo this class is made private https://jar-download.com/artifacts/com.google.truth.extensions/truth-proto-extension/0.39/source-code/com/google/common/truth/extensions/proto/MessageDifferencer.java. Any way I can use truth library to receive a boolean instead of assert for Message comparisons that you might be aware of?

**Comment by oferb** [comment]
Maybe you can send them a PR? :-)
It's just a small 1 word change :-))

> Any way I can use truth library to receive a boolean instead of assert for Message comparisons that you might be aware of?
I'm not well-acquainted with that code, so I don't know.

But you can also just copy the class and use it.. or maybe in the meantime until they accept your PR :))

**Comment by sumitbh250** [comment]
I tried copying the class locally but faced compilation issue of dependency
`MessageDifferencer.java:[484,17] error: cannot find symbol
[ERROR] symbol:   class AutoValue_MessageDifferencer_SpecificField
[ERROR] location: class SpecificField`

I have added auto.value and auto.value.annotation to dependencies
`    <dependency>
      <groupId>com.google.auto.value</groupId>
      <artifactId>auto-value-annotations</artifactId>
      <version>1.7</version>
    </dependency>
    <dependency>
      <groupId>com.google.auto.value</groupId>
      <artifactId>auto-value</artifactId>
      <version>1.7</version>
      <scope>provided</scope>
    </dependency>`

**Comment by sumitbh250** [comment]
I'll mark this as resolved here. Thanks for the help :)

**Comment by ghost** [comment]
Hi @sumitbh250 , did you manage to use this MessageDifferencer class?

**Comment by drather19** [comment]
@frankfighton fyi, if you'd like to use `MessageDifferencer`, you can do so so long as you include the following dependencies (gradle example given):

```
    compile "com.google.auto.value:auto-value-annotations:1.7"
    annotationProcessor "com.google.auto.value:auto-value:1.7"
```

**Comment by lan-n-tran** [comment]
@sumitbh250 so you ended up copy the class to your local and updated the dependency like @drather19 mentioned? MessageDifferencer is exactly what I am looking for.

I see there is an open issue here https://github.com/google/truth/issues/656
